# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20fb0b4d3d5acbe9fad96703907e31e9ba1995e77c01565fec8d50bf13db96d38cd380da3ba52243cd762d24c36a9827ee6b0036b8f2e0c1b9ba18583e229b06

test:
  secret_key_base: e168b998df998fcc155881202f50a9217861f7ee2fda77636879b0e29851e34d67e2a5df6687ea78082569fbcf74850160fc90a83ee6a937ae2f4fe03a18392f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
